import java.util.ArrayList;
import java.util.Hashtable;

public class GiftDatabase {
	/*create a hashmap called gift database that stores gifts recommended for each person
	 * key = person name
	 * value = list of gift ideas
	 */
	static Hashtable recommendedGifts = new Hashtable();

	/*store array lists of random gift ideas for different demographics in alternating thirds: 
	 	*first index = gift name
	 	**2nd = price range
	 	*3rd = link to gift example
	 	*4th = beginning of next gift cycle
	 */
	
	public void createGiftDatabase(){
		
		//gifts for girls ages 0-4
		ArrayList<String> babyGirlGifts = new ArrayList<String>();
		babyGirlGifts.add("Onesie");
		babyGirlGifts.add("10-30");
		babyGirlGifts.add("http://goo.gl/lCFUex");
		babyGirlGifts.add("Shoes");
		babyGirlGifts.add("5-25");
		babyGirlGifts.add("http://goo.gl/3JJHfN");
		babyGirlGifts.add("Bath Toys");
		babyGirlGifts.add("5-10");
		babyGirlGifts.add("http://goo.gl/GyvoFY");
		babyGirlGifts.add("Blanket");
		babyGirlGifts.add("5-20");
		babyGirlGifts.add("http://goo.gl/hTtzBr");
		babyGirlGifts.add("Swaddle");
		babyGirlGifts.add("10-40");
		babyGirlGifts.add("http://goo.gl/HE8lsz");
		babyGirlGifts.add("Clothing Set");
		babyGirlGifts.add("5-15");
		babyGirlGifts.add("http://goo.gl/F1rveJ");
		babyGirlGifts.add("Play Matt");
		babyGirlGifts.add("40-100");
		babyGirlGifts.add("http://goo.gl/9P4LdJ");
		babyGirlGifts.add("Learning Toy");
		babyGirlGifts.add("15-30");
		babyGirlGifts.add("http://goo.gl/VcWSQt");
		babyGirlGifts.add("Stuffed Animal");
		babyGirlGifts.add("5-20");
		babyGirlGifts.add("http://goo.gl/zBRw7H");
		babyGirlGifts.add("Dress");
		babyGirlGifts.add("10-30");
		babyGirlGifts.add("http://goo.gl/YFdSnt");
		

		//gifts for boys ages 0-4
		ArrayList<String> babyBoyGifts = new ArrayList<String>();
		babyBoyGifts.add("Onesie");
		babyBoyGifts.add("10-30");
		babyBoyGifts.add("https://goo.gl/Qmno6k");
		babyBoyGifts.add("Onesie");
		babyBoyGifts.add("10-30");
		babyBoyGifts.add("https://goo.gl/nNVAJP");
		babyBoyGifts.add("Bath Toys");
		babyBoyGifts.add("5-10");
		babyBoyGifts.add("http://goo.gl/GyvoFY");
		babyBoyGifts.add("Blanket");
		babyBoyGifts.add("10-20");
		babyBoyGifts.add("http://goo.gl/5Sbj2Q");
		babyBoyGifts.add("Swaddle");
		babyBoyGifts.add("10-40");
		babyBoyGifts.add("http://goo.gl/HYMQ8R");
		babyBoyGifts.add("Play Matt");
		babyBoyGifts.add("40-70");
		babyBoyGifts.add("http://goo.gl/9P4LdJ");
		babyBoyGifts.add("Pants");
		babyBoyGifts.add("10-25");
		babyBoyGifts.add("http://goo.gl/ArYb9j");
		babyBoyGifts.add("Shirt");
		babyBoyGifts.add("5-15");
		babyBoyGifts.add("http://goo.gl/sNshMy");
		babyBoyGifts.add("Stuffed Animal");
		babyBoyGifts.add("5-20");
		babyBoyGifts.add("http://goo.gl/lkW5bb");
		babyBoyGifts.add("Learning Toy");
		babyBoyGifts.add("15-30");
		babyBoyGifts.add("http://goo.gl/d54NTj");
		

		//gifts for girls ages 5-8
		ArrayList<String> girlGifts = new ArrayList<String>();
		girlGifts.add("Book");
		girlGifts.add("5-20");
		girlGifts.add("http://goo.gl/IHqGq7");
		girlGifts.add("Watch");
		girlGifts.add("10-20");
		girlGifts.add("http://goo.gl/Z2vkyn");
		girlGifts.add("Fancy Doll");
		girlGifts.add("50-100");
		girlGifts.add("http://goo.gl/J831Rh");
		girlGifts.add("Play-Set");
		girlGifts.add("50-100");
		girlGifts.add("http://goo.gl/2utSqp");
		girlGifts.add("Shirt");
		girlGifts.add("15-40");
		girlGifts.add("http://goo.gl/BF0s05");
		girlGifts.add("Pants/Skirt");
		girlGifts.add("15-30");
		girlGifts.add("http://goo.gl/q4BiMl");
		girlGifts.add("Dress");
		girlGifts.add("30-100");
		girlGifts.add("http://goo.gl/WPGXWf");
		girlGifts.add("Shoes");
		girlGifts.add("25-50");
		girlGifts.add("http://goo.gl/W6RNbz");
		girlGifts.add("Makeup Kit");
		girlGifts.add("5-15");
		girlGifts.add("http://goo.gl/oLCBxf");
		girlGifts.add("Accesories");
		girlGifts.add("10-25");
		girlGifts.add("http://goo.gl/eiuzuW");

		//gifts for boys ages 5-8
		ArrayList<String> boyGifts = new ArrayList<String>();
		boyGifts.add("Shoes");
		boyGifts.add("25-50");
		boyGifts.add("http://goo.gl/KRxlvS");
		boyGifts.add("Book");
		boyGifts.add("5-20");
		boyGifts.add("http://goo.gl/JgDcQ8");
		boyGifts.add("Play-Set");
		boyGifts.add("10-30");
		boyGifts.add("http://goo.gl/QIbUbv");
		boyGifts.add("Sports Equipment");
		boyGifts.add("10-20");
		boyGifts.add("http://goo.gl/arQyfX");
		boyGifts.add("Shirt");
		boyGifts.add("10-25");
		boyGifts.add("http://goo.gl/3C12gb");
		boyGifts.add("Pants");
		boyGifts.add("20-50");
		boyGifts.add("http://goo.gl/pw2wc1");
		boyGifts.add("Jacket");
		boyGifts.add("20-50");
		boyGifts.add("http://goo.gl/QjQgCt");
		boyGifts.add("Watch");
		boyGifts.add("10-20");
		boyGifts.add("http://goo.gl/sc4TMd");
		boyGifts.add("Toy");
		boyGifts.add("20-40");
		boyGifts.add("http://goo.gl/8gGwYa");
		boyGifts.add("Accesory");
		boyGifts.add("10-20");
		boyGifts.add("http://goo.gl/IBF9vT");

		//gifts for boys ages 9-12
		ArrayList<String> preteenBoyGifts = new ArrayList<String>();
		preteenBoyGifts.add("Sports Related Gifts");
		preteenBoyGifts.add("20-40");
		preteenBoyGifts.add("http://goo.gl/E28ayi");
		preteenBoyGifts.add("Book Set");
		preteenBoyGifts.add("10-20");
		preteenBoyGifts.add("http://goo.gl/disuFt");
		preteenBoyGifts.add("Build/Science Set");
		preteenBoyGifts.add("10-20");
		preteenBoyGifts.add("http://goo.gl/23M1vr");
		preteenBoyGifts.add("Shirt");
		preteenBoyGifts.add("15-25");
		preteenBoyGifts.add("http://goo.gl/XNmXVb");
		preteenBoyGifts.add("Pants");
		preteenBoyGifts.add("http://goo.gl/bOqdNm");
		preteenBoyGifts.add("15-30");
		preteenBoyGifts.add("Jacket");
		preteenBoyGifts.add("10-30");
		preteenBoyGifts.add("http://goo.gl/ecqDJQ");
		preteenBoyGifts.add("Giftcard");
		preteenBoyGifts.add("your choice");
		preteenBoyGifts.add("http://goo.gl/it65Fk");
		preteenBoyGifts.add("Accesories");
		preteenBoyGifts.add("10-20");
		preteenBoyGifts.add("http://goo.gl/hA8b0c");
		preteenBoyGifts.add("Body Care Products (ex: cologne)");
		preteenBoyGifts.add("10-20");
		preteenBoyGifts.add("http://goo.gl/OWrmJ1");
		

		//gifts for girls ages 9-12
		ArrayList<String> preteenGirlGifts = new ArrayList<String>();
		preteenGirlGifts.add("Sports Gift");
		preteenGirlGifts.add("10-30");
		preteenGirlGifts.add("http://goo.gl/K9GgmB");
		preteenGirlGifts.add("Giftcard");
		preteenGirlGifts.add("your choice"); //WATCH OUT WHEN PRICE STRING --> INT
		preteenGirlGifts.add("http://goo.gl/it65Fk");
		preteenGirlGifts.add("Accesories");
		preteenGirlGifts.add("10-30");
		preteenGirlGifts.add("http://goo.gl/uiaMTK");
		preteenGirlGifts.add("Book Set");
		preteenGirlGifts.add("10-20");
		preteenGirlGifts.add("http://goo.gl/disuFt");
		preteenGirlGifts.add("Build/Science Set");
		preteenGirlGifts.add("10-20");
		preteenGirlGifts.add("http://goo.gl/23M1vr");
		preteenGirlGifts.add("Dress");
		preteenGirlGifts.add("15-30");
		preteenGirlGifts.add("http://goo.gl/BBjDqV");
		preteenGirlGifts.add("Skirt");
		preteenGirlGifts.add("10-25");
		preteenGirlGifts.add("http://goo.gl/GixWs4");
		preteenGirlGifts.add("Pants");
		preteenGirlGifts.add("15-30");
		preteenGirlGifts.add("http://goo.gl/UlSCXn");
		preteenGirlGifts.add("Shirt");
		preteenGirlGifts.add("10-25");
		preteenGirlGifts.add("http://goo.gl/SMxbWQ");
		preteenGirlGifts.add("Makeup/Nail Polish");
		preteenGirlGifts.add("10-20");
		preteenGirlGifts.add("http://goo.gl/pYwJpn");
		

		//gifts for girls ages 13-19
		ArrayList<String> teenGirlGifts = new ArrayList<String>();
		teenGirlGifts.add("Giftcard");
		teenGirlGifts.add("you choose");
		teenGirlGifts.add("http://goo.gl/1rE677");
		teenGirlGifts.add("Pants");
		teenGirlGifts.add("30-50");
		teenGirlGifts.add("https://goo.gl/yW41lQ");
		teenGirlGifts.add("Skirt");
		teenGirlGifts.add("20-40");
		teenGirlGifts.add("https://goo.gl/4fdF3r");
		teenGirlGifts.add("Dress/Romper");
		teenGirlGifts.add("20-40");
		teenGirlGifts.add("https://goo.gl/1wZyTo");
		teenGirlGifts.add("Shirt");
		teenGirlGifts.add("10-30");
		teenGirlGifts.add("https://goo.gl/rmW1CL");
		teenGirlGifts.add("Jacket");
		teenGirlGifts.add("30-70");
		teenGirlGifts.add("http://goo.gl/3dygdY");
		teenGirlGifts.add("Shoes");
		teenGirlGifts.add("25-50");
		teenGirlGifts.add("https://goo.gl/xKvpTv");
		teenGirlGifts.add("Accesory");
		teenGirlGifts.add("5-40");
		teenGirlGifts.add("http://goo.gl/rYNEd7");
		teenGirlGifts.add("Makeup/Nail Polish");
		teenGirlGifts.add("20-50");
		teenGirlGifts.add("http://goo.gl/Tp9WaE");
		teenGirlGifts.add("Book");
		teenGirlGifts.add("5-30");
		teenGirlGifts.add("http://goo.gl/WXc8vF");

		//gifts for boys ages 13-19
		ArrayList<String> teenBoyGifts = new ArrayList<String>();
		teenBoyGifts.add("Giftcard");
		teenBoyGifts.add("you choose");
		teenBoyGifts.add("http://goo.gl/1rE677");
		teenBoyGifts.add("Book");
		teenBoyGifts.add("5-30");
		teenBoyGifts.add("http://goo.gl/WXc8vF");
		teenBoyGifts.add("Body Care Products (ex: cologne)");
		teenBoyGifts.add("15-30");
		teenBoyGifts.add("http://goo.gl/8Vvsp1");
		teenBoyGifts.add("Sports Gifts");
		teenBoyGifts.add("15-30");
		teenBoyGifts.add("http://goo.gl/32pfml");
		teenBoyGifts.add("Shirt");
		teenBoyGifts.add("15-30");
		teenBoyGifts.add("https://goo.gl/0oYWkA");
		teenBoyGifts.add("Pants");
		teenBoyGifts.add("20-40");
		teenBoyGifts.add("https://goo.gl/dhESQE");
		teenBoyGifts.add("Jacket");
		teenBoyGifts.add("30-60");
		teenBoyGifts.add("https://goo.gl/35NnXu");
		teenBoyGifts.add("Accesory");
		teenBoyGifts.add("10-20");
		teenBoyGifts.add("https://goo.gl/Tkm3GF");
		teenBoyGifts.add("Shoes");
		teenBoyGifts.add("20-30");
		teenBoyGifts.add("https://goo.gl/i4Nhw6");
		teenBoyGifts.add("Headphones");
		teenBoyGifts.add("100-300");
		teenBoyGifts.add("http://goo.gl/BzbRTu");

		//gifts for girls ages 20-35
		ArrayList<String> youngFemaleAdultGifts = new ArrayList<String>();
		youngFemaleAdultGifts.add("Shirt");
		youngFemaleAdultGifts.add("10-30");
		youngFemaleAdultGifts.add("https://goo.gl/CAKvSM");
		youngFemaleAdultGifts.add("Shoes");
		youngFemaleAdultGifts.add("25-50");
		youngFemaleAdultGifts.add("http://goo.gl/D2WJIY");
		youngFemaleAdultGifts.add("Jewelry");
		youngFemaleAdultGifts.add("40-100");
		youngFemaleAdultGifts.add("http://goo.gl/8p4YX7");
		youngFemaleAdultGifts.add("Accesory");
		youngFemaleAdultGifts.add("5-40");
		youngFemaleAdultGifts.add("https://goo.gl/bM7BOC");
		youngFemaleAdultGifts.add("Makeup/Nail Polish");
		youngFemaleAdultGifts.add("20-50");
		youngFemaleAdultGifts.add("http://goo.gl/Tp9WaE");
		youngFemaleAdultGifts.add("Giftcard");
		youngFemaleAdultGifts.add("you choose");
		youngFemaleAdultGifts.add("http://goo.gl/1rE677");
		youngFemaleAdultGifts.add("Concert Tickets");
		youngFemaleAdultGifts.add("30-200");
		youngFemaleAdultGifts.add("http://goo.gl/Ojipcq");
		youngFemaleAdultGifts.add("Personalized Computer/Phone Case");
		youngFemaleAdultGifts.add("20-40");
		youngFemaleAdultGifts.add("http://goo.gl/BK4zsj");
		youngFemaleAdultGifts.add("Alcohol");
		youngFemaleAdultGifts.add("20-50");
		youngFemaleAdultGifts.add("http://goo.gl/VzVAyA");
		youngFemaleAdultGifts.add("Skirt");
		youngFemaleAdultGifts.add("20-40");
		youngFemaleAdultGifts.add("https://goo.gl/opKXjm");
		youngFemaleAdultGifts.add("DressDress/Romper");
		youngFemaleAdultGifts.add("20-40");
		youngFemaleAdultGifts.add("http://goo.gl/KIU2lF");
		youngFemaleAdultGifts.add("Pants");
		youngFemaleAdultGifts.add("20-50");
		youngFemaleAdultGifts.add("https://goo.gl/YuSIUq");
		youngFemaleAdultGifts.add("Jacket");
		youngFemaleAdultGifts.add("30-70");
		youngFemaleAdultGifts.add("https://goo.gl/Fm4L7I");
		youngFemaleAdultGifts.add("Sports Tickets");
		youngFemaleAdultGifts.add("30-200");
		youngFemaleAdultGifts.add("http://goo.gl/RzrjEd");
		youngFemaleAdultGifts.add("Accesory");
		youngFemaleAdultGifts.add("5-40");
		youngFemaleAdultGifts.add("https://goo.gl/IRczuh");
		youngFemaleAdultGifts.add("Fancy Shoes");
		youngFemaleAdultGifts.add("100-300");
		youngFemaleAdultGifts.add("http://goo.gl/DLuro4");
		youngFemaleAdultGifts.add("Formal Dress");
		youngFemaleAdultGifts.add("100-200");
		youngFemaleAdultGifts.add("http://goo.gl/IoobNt");

	
		
		//gifts for boys ages 20-35
		ArrayList<String> youngMaleAdultGifts = new ArrayList<String>();
		youngMaleAdultGifts.add("Concert Tickets");
		youngMaleAdultGifts.add("30-200");
		youngMaleAdultGifts.add("http://goo.gl/Ojipcq");
		youngMaleAdultGifts.add("Giftcard");
		youngMaleAdultGifts.add("you choose");
		youngMaleAdultGifts.add("http://goo.gl/1rE677");
		youngMaleAdultGifts.add("Personalized Computer/Phone Case");
		youngMaleAdultGifts.add("20-40");
		youngMaleAdultGifts.add("http://goo.gl/BK4zsj");
		youngMaleAdultGifts.add("Alcohol");
		youngMaleAdultGifts.add("20-50");
		youngMaleAdultGifts.add("http://goo.gl/VzVAyA");
		youngMaleAdultGifts.add("Shirt");
		youngMaleAdultGifts.add("30-50");
		youngMaleAdultGifts.add("http://goo.gl/OUatP3");
		youngMaleAdultGifts.add("Pants");
		youngMaleAdultGifts.add("30-50");
		youngMaleAdultGifts.add("https://goo.gl/HzETbt");
		youngMaleAdultGifts.add("Jacket");
		youngMaleAdultGifts.add("30-150");
		youngMaleAdultGifts.add("http://goo.gl/qoGB3N");
		youngMaleAdultGifts.add("Body Care Products (ex: cologne)");
		youngMaleAdultGifts.add("50-100");
		youngMaleAdultGifts.add("http://goo.gl/gzhQEn");
		youngMaleAdultGifts.add("Accesory");
		youngMaleAdultGifts.add("10-30");
		youngMaleAdultGifts.add("http://goo.gl/JB0TTd");
		youngMaleAdultGifts.add("Sports Tickets");
		youngMaleAdultGifts.add("30-200");
		youngMaleAdultGifts.add("http://goo.gl/RzrjEd");
		youngMaleAdultGifts.add("Headphones");
		youngMaleAdultGifts.add("100-300");
		youngMaleAdultGifts.add("http://goo.gl/BzbRTu");
		youngMaleAdultGifts.add("Suit");
		youngMaleAdultGifts.add("150-300");
		youngMaleAdultGifts.add("http://goo.gl/Zcqjhz");
		youngMaleAdultGifts.add("Tie");
		youngMaleAdultGifts.add("50-100");
		youngMaleAdultGifts.add("http://goo.gl/0i1Sk6");
		

		//gifts for girls ages 36+
		ArrayList<String> femaleAdultGifts = new ArrayList<String>();
		femaleAdultGifts.add("Alcohol");
		femaleAdultGifts.add("20-50");
		femaleAdultGifts.add("http://goo.gl/VzVAyA");
		femaleAdultGifts.add("Giftcard");
		femaleAdultGifts.add("you choose");
		femaleAdultGifts.add("http://goo.gl/1rE677");
		femaleAdultGifts.add("Personalized Computer/Phone Case");
		femaleAdultGifts.add("20-40");
		femaleAdultGifts.add("http://goo.gl/BK4zsj");
		femaleAdultGifts.add("Book");
		femaleAdultGifts.add("10-30");
		femaleAdultGifts.add("http://goo.gl/IvMe7r");
		femaleAdultGifts.add("Shirt");
		femaleAdultGifts.add("50-100");
		femaleAdultGifts.add("http://goo.gl/Gpo94K");
		femaleAdultGifts.add("Jacket");
		femaleAdultGifts.add("100-200");
		femaleAdultGifts.add("http://goo.gl/EblQyM");
		femaleAdultGifts.add("Formal Dress");
		femaleAdultGifts.add("150-300");
		femaleAdultGifts.add("http://goo.gl/hK0i83");
		femaleAdultGifts.add("Pants");
		femaleAdultGifts.add("30-50");
		femaleAdultGifts.add("http://goo.gl/fJwCvA");
		femaleAdultGifts.add("Fancy Shoes");
		femaleAdultGifts.add("100-300");
		femaleAdultGifts.add("http://goo.gl/DLuro4");
		femaleAdultGifts.add("Jewlery");
		femaleAdultGifts.add("70-200");
		femaleAdultGifts.add("http://goo.gl/2AmgFt");
		femaleAdultGifts.add("Purse/Wallet");
		femaleAdultGifts.add("200-400");
		femaleAdultGifts.add("http://goo.gl/tuR2oX");
		femaleAdultGifts.add("Watch");
		femaleAdultGifts.add("150-300");
		femaleAdultGifts.add("http://goo.gl/86f0hG");

		//gifts for boys ages 36+
		ArrayList<String> maleAdultGifts = new ArrayList<String>();
		maleAdultGifts.add("Alcohol");
		maleAdultGifts.add("20-50");
		maleAdultGifts.add("http://goo.gl/VzVAyA");
		maleAdultGifts.add("Giftcard");
		maleAdultGifts.add("you choose");
		maleAdultGifts.add("http://goo.gl/1rE677");
		maleAdultGifts.add("Pants");
		maleAdultGifts.add("40-100");
		maleAdultGifts.add("http://goo.gl/1wd4Ev");
		maleAdultGifts.add("Shirt");
		maleAdultGifts.add("30-50");
		maleAdultGifts.add("http://goo.gl/x4smto");
		maleAdultGifts.add("Suit");
		maleAdultGifts.add("150-300");
		maleAdultGifts.add("http://goo.gl/Zcqjhz");
		maleAdultGifts.add("Personalized Computer/Phone Case");
		maleAdultGifts.add("20-40");
		maleAdultGifts.add("http://goo.gl/BK4zsj");
		maleAdultGifts.add("Jacket");
		maleAdultGifts.add("150-300");
		maleAdultGifts.add("http://goo.gl/jPFqzE");
		maleAdultGifts.add("Tie");
		maleAdultGifts.add("50-100");
		maleAdultGifts.add("http://goo.gl/0i1Sk6");
		maleAdultGifts.add("Shoes");
		maleAdultGifts.add("50-100");
		maleAdultGifts.add("http://goo.gl/7kmjmi");
		maleAdultGifts.add("Book");
		maleAdultGifts.add("10-30");
		maleAdultGifts.add("http://goo.gl/IvMe7r");
		maleAdultGifts.add("Wallet");
		maleAdultGifts.add("50-100");
		maleAdultGifts.add("http://goo.gl/jbyqxL");
		maleAdultGifts.add("Cufflinks");
		maleAdultGifts.add("50-100");
		maleAdultGifts.add("http://goo.gl/7rXsxz");
		maleAdultGifts.add("Watch");
		maleAdultGifts.add("200-500");
		maleAdultGifts.add("http://goo.gl/fbGvgh");
		maleAdultGifts.add("Body Care Products (ex: cologne)");
		maleAdultGifts.add("50-100");
		maleAdultGifts.add("http://goo.gl/gzhQEn");

		

		//gifts for nerds!
		ArrayList<String> nerdGifts = new ArrayList<String>();
		nerdGifts.add("Gadget Fighting Toy");
		nerdGifts.add("100-200");
		nerdGifts.add("http://goo.gl/mmKBGb");
		nerdGifts.add("Batman Electrical Outlet Sticker");
		nerdGifts.add("2-5");
		nerdGifts.add("http://goo.gl/E13E7E");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");

		//gifts for athletes
		ArrayList<String> athleteGifts = new ArrayList<String>();
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");

		//gifts for artists
		ArrayList<String> artistGifts = new ArrayList<String>();
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");

		//gifts for travelers/the outdoorsy type
		ArrayList<String> outdoorsyGifts = new ArrayList<String>();
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");

		//gifts for girls that are fashion and makeup lovers
		ArrayList<String> girlFashionistaGifts = new ArrayList<String>();
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");

		//gifts for boys that are fashion lovers
		ArrayList<String> boyFashionistaGifts = new ArrayList<String>();
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		

		//gifts for people that love movies, plays, museums, and music
		ArrayList<String> entertainementBuffGifts = new ArrayList<String>();
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");

	}
}

	