import java.util.ArrayList;
import java.util.Hashtable;

public class GiftDatabase {
	/*create a hashmap called gift database that stores gifts recommended for each person
	 * key = person name
	 * value = list of gift ideas
	 */
	static Hashtable recommendedGifts = new Hashtable();

	/*store array lists of random gift ideas for different demographics in alternating thirds: 
	 	*first index = gift name
	 	*2nd = link to gift example
	 	*3rd = price range
	 	*4th = beginning of next gift cycle
	 */
	
	public void createGiftDatabase(){
		
		//gifts for girls ages 0-4
		ArrayList<String> babyGirlGifts = new ArrayList<String>();
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		babyGirlGifts.add("");
		

		//gifts for boys ages 0-4
		ArrayList<String> babyBoyGifts = new ArrayList<String>();
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		babyBoyGifts.add("");
		

		//gifts for girls ages 5-8
		ArrayList<String> girlGifts = new ArrayList<String>();
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");
		girlGifts.add("");

		//gifts for boys ages 5-8
		ArrayList<String> boyGifts = new ArrayList<String>();
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");
		boyGifts.add("");

		//gifts for boys ages 9-12
		ArrayList<String> preteenBoyGifts = new ArrayList<String>();
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");
		preteenBoyGifts.add("");

		//gifts for girls ages 9-12
		ArrayList<String> preteenGirlGifts = new ArrayList<String>();
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");
		preteenGirlGifts.add("");

		//gifts for girls ages 13-19
		ArrayList<String> teenGirlGifts = new ArrayList<String>();
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");
		teenGirlGifts.add("");

		//gifts for boys ages 13-19
		ArrayList<String> teenBoyGifts = new ArrayList<String>();
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");
		teenBoyGifts.add("");

		//gifts for girls ages 20-29
		ArrayList<String> youngFemaleAdultGifts = new ArrayList<String>();
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		youngFemaleAdultGifts.add("");
		
		//gifts for boys ages 20-29
		ArrayList<String> youngMaleAdultGifts = new ArrayList<String>();
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");
		youngMaleAdultGifts.add("");

		//gifts for girls ages 30-45
		ArrayList<String> femaleAdultGifts = new ArrayList<String>();
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");
		femaleAdultGifts.add("");

		//gifts for boys ages 30-45
		ArrayList<String> maleAdultGifts = new ArrayList<String>();
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");
		maleAdultGifts.add("");

		//gifts for girls ages 46-60
		ArrayList<String> olderFemaleAdultGifts = new ArrayList<String>();
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");
		olderFemaleAdultGifts.add("");

		//gifts for boys ages 46-60
		ArrayList<String> olderMaleAdultGifts = new ArrayList<String>();
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");
		olderMaleAdultGifts.add("");

		//gifts for girls ages 60-
		ArrayList<String> oldFemaleAdultGifts = new ArrayList<String>();
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");
		oldFemaleAdultGifts.add("");

		//gifts for boys ages 60-
		ArrayList<String> oldMaleAdultGifts = new ArrayList<String>();
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");
		oldMaleAdultGifts.add("");

		//gifts for nerds!
		ArrayList<String> nerdGifts = new ArrayList<String>();
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");
		nerdGifts.add("");

		//gifts for athletes
		ArrayList<String> athleteGifts = new ArrayList<String>();
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");
		athleteGifts.add("");

		//gifts for artists
		ArrayList<String> artistGifts = new ArrayList<String>();
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");
		artistGifts.add("");

		//gifts for travelers/the outdoorsy type
		ArrayList<String> outdoorsyGifts = new ArrayList<String>();
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");
		outdoorsyGifts.add("");

		//gifts for girls that are fashion and makeup lovers
		ArrayList<String> girlFashionistaGifts = new ArrayList<String>();
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");
		girlFashionistaGifts.add("");

		//gifts for boys that are fashion lovers
		ArrayList<String> boyFashionistaGifts = new ArrayList<String>();
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		boyFashionistaGifts.add("");
		

		//gifts for people that love movies, plays, museums, and music
		ArrayList<String> entertainementBuffGifts = new ArrayList<String>();
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");
		entertainementBuffGifts.add("");

	}
}

	